name: TasksPlanner
description: "A simple to-do list app."
publish_to: 'none' 

version: 1.1.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  animated_text_kit: ^4.2.2
  modal_progress_hud_nsn: ^0.5.1
  cloud_firestore: ^4.17.0
  rxdart: ^0.27.7
  async: ^2.11.0
  google_fonts: ^6.2.1
  dotted_line: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
